[versions]
# libraries
annotations = "24.0.1"
remoteRobot = "0.11.18"

# plugins
dokka = "1.8.20"
kotlin = "1.8.22"
changelog = "2.1.0"
gradleIntelliJPlugin = "1.14.2"
qodana = "0.1.13"
kover = "0.7.2"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version.ref = "annotations" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradleIntelliJPlugin = { id = "org.jetbrains.intellij", version.ref = "gradleIntelliJPlugin" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }